evo_config:
  _target_: shinka.core.EvolutionConfig
  patch_types:
  - diff
  - full
  - cross
  patch_type_probs:
  - 0.4
  - 0.4
  - 0.2
  num_generations: 100
  max_parallel_jobs: 10
  max_patch_resamples: 2
  max_patch_attempts: 2
  llm_models:
  - GOOGLE_GEMINI-2.5-PRO
  - GOOGLE_GEMINI-2.5-FLASH
  llm_dynamic_selection: ucb
  llm_kwargs:
    temperatures:
    - 0.7
    - 0.7
    max_tokens: 2147483647
  meta_rec_interval: 10
  meta_llm_models:
  - GOOGLE_GEMINI-2.5-PRO
  meta_llm_kwargs:
    temperatures:
    - 0.7
  embedding_model: AZURE_TEXT-EMBEDDING-3-SMALL
  results_dir: ${output_dir}